
// ===================== FIREBASE =====================
const firebaseConfig = {
  apiKey: "AIzaSyBrvvXKGZwKX1VOU-C6WZvB98r1KO9I5HI",
  authDomain: "f6ad-2913b.firebaseapp.com",
  projectId: "f6ad-2913b",
  storageBucket: "f6ad-2913b.firebasestorage.app",
  messagingSenderId: "1000483275960",
  appId: "1:1000483275960:web:f9f9974965854a5cbfa04d"
};
firebase.initializeApp(firebaseConfig);
const db = firebase.firestore();

// ===================== DATA =====================
const CONFIRMED_IDS = [8, 13, 20, 6];
const POSSIBILITY_IDS = [6];

const SUMMER_TOURNAMENTS = [
  {id:1,name:"CRUSA Invitational (17th Annual)",host:"FC Bucks",location:"Richboro, PA",distance:30,dates:"Aug 1-2, 2026",format:"11v11",fee:"$800",deadline:"Jul 10, 2026",website:"fcbucks.com/august-invitational-tournament/",notes:"Uses new Fall 2026 Aug-Jul age matrix. Premier preseason testing ground."},
  {id:2,name:"Kearny Skyline Cup",host:"iSE",location:"Kearny/Harrison, NJ",distance:100,dates:"Jun 13-14, 2026",format:"11v11",fee:"$970",deadline:"May 29, 2026",website:"isportingevents.com/kearnyskylinecup",notes:"Multi-team discounts. Rich soccer history."},
  {id:3,name:"EDP Summer Sizzler",host:"EDP Soccer",location:"Hammonton, NJ",distance:70,dates:"Jul 25-26, 2026",format:"11v11",fee:"$1,295 early / $1,395 regular",deadline:"Jun 26, 2026",website:"edpsoccer.com/summer-sizzler",notes:"Capstone EDP Summer Series. Stay-to-Play via Team Travel Source."},
  {id:4,name:"Greystone Cup",host:"iSE",location:"Budd Lake, NJ",distance:90,dates:"Jul 25-26, 2026",format:"11v11",fee:"$970",deadline:"Jul 10, 2026",website:"isportingevents.com/greystonecup",notes:"Elite + Premier flights. Multi-team discounts."},
  {id:5,name:"Philly Summer Shootout",host:"Philadelphia Union / S3",location:"Chester, PA",distance:30,dates:"Jul 25-26, 2026",format:"Verify 11v11",fee:"$1,195",deadline:"Jun 24, 2026",website:"sidelinesoccersolutions.com/events-connecter/philly-summer-shootout",notes:"VERIFY 11v11 FORMAT before registering."},
  {id:6,name:"Penn Fusion Summer Classic (38th Annual)",host:"Penn Fusion SA / S3",location:"West Chester, PA",distance:25,dates:"Aug 8-9, 2026",format:"11v11",fee:"TBD (~$700-$850)",deadline:"Via GotSport",website:"pennfusion.org/tournaments",notes:"38th annual. 1-day boys format for 2026. Excellent pre-fall tune-up."},
  {id:7,name:"Philadelphia Union Summer Cooldown",host:"Philadelphia Union / S3",location:"Chester, PA",distance:20,dates:"Aug 8-9, 2026",format:"11v11 likely",fee:"TBD",deadline:"TBD",website:"philadelphiaunion.com/youth/tournaments/home",notes:"May be U8-U12 only. Confirm U14 availability before registering."},
  {id:8,name:"The Cup 26",host:"Philadelphia Union Youth",location:"Chester, PA",distance:20,dates:"Jun 6-7, 2026",format:"11v11; 2x30-min halves; turf",fee:"$1,300 early / $1,500 standard",deadline:"Standard: May 1, 2026",website:"philadelphiaunion.com/youth/tournaments/the_cup",notes:"MLS-affiliated facility. ~8 teams per division. Elite standards, scouting presence."},
  {id:9,name:"Lehigh Valley YSL Tournament (46th Annual)",host:"Lehigh Valley YSL / S3",location:"Allentown, PA",distance:55,dates:"Jun 6-7, 2026",format:"11v11",fee:"TBD",deadline:"TBD",website:"sidelinesoccersolutions.com",notes:"46th annual. Awards for 1st and 2nd place."},
  {id:10,name:"Lancaster Summer Classic",host:"Lancaster Elite + Manheim Township SC",location:"Lancaster, PA",distance:65,dates:"Jun 6-7, 2026",format:"11v11",fee:"$850",deadline:"May 13, 2026",website:"lancastersummerclassic.com",notes:"GotSport ranking points. College coaches for older brackets."},
  {id:11,name:"Leon Grenko Soccer Tournament",host:"Berks County",location:"Reading, PA",distance:45,dates:"Jun 6-7, 2026",format:"11v11",fee:"TBD",deadline:"TBD",website:"GotSport: Leon Grenko",notes:"Long-standing community event. Lower-pressure, lower-cost option."},
  {id:12,name:"PA Classics Mid-Atlantic Cup (19th Annual)",host:"Pennsylvania Classics AC",location:"Manheim, PA",distance:65,dates:"Jun 13-14, 2026",format:"11v11",fee:"$875",deadline:"Mid-May 2026",website:"paclassics.org/mid-atlantic-cup",notes:"Cornerstone EPYSA event. Discounted Hersheypark tickets."},
  {id:13,name:"EDP Summer Classic",host:"EDP Soccer",location:"Hammonton, NJ",distance:80,dates:"Jun 20-21, 2026",format:"11v11",fee:"$1,295 early / $1,395 regular",deadline:"May 8, 2026",website:"edpsoccer.com/summer-classic",notes:"Flagship EDP summer event. Draws MLS Next, ECNL, NL teams. Up to 5 guest players."},
  {id:14,name:"Hershey Summer Classic",host:"Hershey Soccer Club",location:"Hershey, PA",distance:95,dates:"Jun 20-21, 2026",format:"11v11",fee:"$1,075",deadline:"May 17, 2026",website:"hersheysoccer.org/summerclassic",notes:"Discounted Hersheypark tickets. ~200 teams expected."},
  {id:15,name:"Liberty Summer Cup",host:"S3",location:"Downingtown/West Chester, PA",distance:25,dates:"Jun 27-28, 2026",format:"11v11",fee:"$800",deadline:"Via GotSport",website:"libertysummercup.com",notes:"Multiple Chester County venues. Excellent value."},
  {id:16,name:"NSA Summer Kickoff (51st Annual)",host:"Neptune Soccer Assoc.",location:"Neptune, NJ",distance:85,dates:"Jun 27-28, 2026",format:"11v11",fee:"$870",deadline:"Via GotSport",website:"neptunesoccer.org/tournament/",notes:"Longest-running NJ tournament. Jersey Shore setting."},
  {id:17,name:"Pocono Mountain Cup",host:"Pocono Mountain Youth SC",location:"Swiftwater, PA",distance:100,dates:"Jun 27-28, 2026",format:"11v11",fee:"$875",deadline:"Jun 12, 2026",website:"poconomountaincup.com",notes:"2nd annual. Cooler altitude. Resort/vacation setting."},
  {id:18,name:"CenPenn Summer Cup",host:"UnitedGoals USA",location:"Manheim, PA",distance:80,dates:"Jun 27-28, 2026",format:"11v11",fee:"$725",deadline:"Contact organizer",website:"unitedgoalsusa.com/cenpenn-youth-soccer-tournament-manheim/",notes:"8+ full-sized grass fields. Strong value."},
  {id:19,name:"Steel United Summer Trophy (12th Annual)",host:"Steel Sports",location:"Montgomery Township, NJ",distance:35,dates:"Jul 11-12, 2026",format:"11v11",fee:"$1,045",deadline:"Jun 12, 2026",website:"steelsports.com/events/summer-trophy/",notes:"Certified athletic trainer on site."},
  {id:20,name:"Lititz Summer Showcase",host:"Lititz Summer Showcase",location:"Lititz/Manheim, PA",distance:75,dates:"Jul 11-12, 2026",format:"11v11",fee:"$850",deadline:"App: Jun 14; Pay: Jun 7",website:"lititzsummershowcase.org",notes:"Date moved earlier in 2026. Halpern Travel required for all teams."},
  {id:21,name:"Central Jersey Invitational",host:"EDP Soccer",location:"Somerset, NJ",distance:75,dates:"Jul 11-12, 2026",format:"11v11",fee:"$1,225 early / $1,325 regular",deadline:"Jun 12, 2026",website:"edpsoccer.com/central-jersey-invitational",notes:"PDA complex. Up to 5 guest players."},
  {id:22,name:"Mid-Atlantic Cup at Maryland SoccerPlex",host:"Maryland SoccerPlex",location:"Boyds, MD",distance:140,dates:"Jun 13-14, 2026",format:"11v11",fee:"TBD",deadline:"Standard May 1; Late May 10",website:"midatlanticcupmd.com",notes:"Champions/finalists receive Washington Spirit match tickets."},
  {id:23,name:"FSCI Summer Classic and Showcase",host:"Fredericksburg Soccer Club",location:"Fredericksburg, VA",distance:190,dates:"Jun 13-14, 2026",format:"11v11",fee:"$875",deadline:"May 10, 2026",website:"fredericksburgsoccer.org/tournaments/june/",notes:"Bermuda grass at VYSA training center. College coaches attend."},
  {id:24,name:"Mason Dixon Cup",host:"Hagerstown SC / Elite Tournaments",location:"Hagerstown, MD",distance:160,dates:"Jun 20-21, 2026",format:"11v11",fee:"TBD + $200 bond",deadline:"Schedules posted Jun 3",website:"elitetournaments.com/tournaments/mason-dixon-cup/",notes:"Running since 1991. Fathers Day weekend."},
  {id:25,name:"Liberty Cup Long Island",host:"TSP / LIJSL",location:"Brentwood, NY",distance:130,dates:"Jul 25-26, 2026",format:"11v11",fee:"$795",deadline:"TBD",website:"GotSport: TSP Liberty Cup 2026",notes:"LIJSL ecosystem. Strict guest player rules."},
  {id:26,name:"Kick-Off Classic",host:"Globall Competitions",location:"Uniondale, NY",distance:110,dates:"Aug 9, 2026",format:"11v11",fee:"TBD",deadline:"TBD",website:"kickoffli.com",notes:"Single-day pre-season primer."},
  {id:27,name:"Maryland Invitational",host:"Bethesda SC and DeMatha Soccer Academy",location:"Boyds, MD",distance:130,dates:"Jun 5-7, 2026",format:"11v11 (verify)",fee:"TBD",deadline:"TBD",website:"USYS MD sanctioned listing",notes:"Premier facility. Verify U14 boys bracket."},
  {id:28,name:"NRSA Fathers Day Cup",host:"North Rockland Soccer Assoc.",location:"Thiells, NY",distance:110,dates:"Jun 20-21, 2026",format:"11v11",fee:"$720",deadline:"TBD",website:"nrsa.org/fdc",notes:"Single-day boys format."},
  {id:29,name:"Independence Cup Long Island (19th Annual)",host:"Globall Competitions",location:"Uniondale, NY",distance:130,dates:"Jun 27, 2026",format:"11v11 for U13+",fee:"TBD",deadline:"TBD",website:"indycupli.com",notes:"Single-day format. 19th annual."},
  {id:30,name:"Pittsburgh Riverhounds Classic",host:"Pittsburgh Riverhounds SC",location:"Pittsburgh, PA",distance:295,dates:"~Aug 29-31, 2026",format:"11v11",fee:"TBD",deadline:"TBD (tournaments@riverhounds.com)",website:"riverhounds.com/riverhounds-sc-tournament-series/",notes:"Annual flagship event of the Riverhounds SC Tournament Series. U9-U15 boys and girls. Professional club atmosphere run by Riverhounds Development Academy staff. Great experience for teams willing to make the western PA trip. Contact: Justin Evans at tournaments@riverhounds.com."}
];

const FALL_TOURNAMENTS = [
  {id:101,name:"Keystone Cup",host:"Pennsylvania Classics AC",location:"Lancaster County, PA",distance:58,dates:"Sep 5-6, 2026",format:"11v11 confirmed",fee:"$975",deadline:"Aug 7, 2026",website:"paclassics.org/keystone-cup",notes:"U14 explicitly 11v11. Multiple Lancaster-area venues incl. Spooky Nook Sports."},
  {id:102,name:"S3 Super Cup",host:"Sideline Soccer Solutions (S3)",location:"Downingtown, PA",distance:22,dates:"Sep 5-6, 2026",format:"11v11 (verify)",fee:"TBD",deadline:"Via registration portal",website:"sidelinesoccersolutions.com/events-connecter/s3-super-cup",notes:"Invitation-only elite event. Only 22 miles away at United Sports, Downingtown."},
  {id:103,name:"EDP Cup Fall 2026",host:"EDP Soccer",location:"Hammonton, NJ",distance:40,dates:"Oct 10-11, 2026",format:"11v11 confirmed",fee:"Published by tier",deadline:"Sep 11, 2026",website:"edpsoccer.com/tournaments",notes:"Multi-venue South Jersey. 11v11 fee tier published."},
  {id:104,name:"Columbus Day Explorer Cup",host:"Sideline Soccer Solutions (S3)",location:"Downingtown, PA",distance:22,dates:"Oct 10-11, 2026",format:"11v11 (U13-U16)",fee:"Verify in registration",deadline:"Via registration portal",website:"sidelinesoccersolutions.com/events-connecter/columbus-day-explorer-cup",notes:"HQ at United Sports, Downingtown. Max 22 for U13-U16, max 18 dressed. Up to 5 guest players."},
  {id:105,name:"Western Lehigh Fall Fest",host:"Western Lehigh United SC",location:"Allentown area, PA",distance:38,dates:"Oct 10-11, 2026",format:"11v11 confirmed",fee:"Verify fees",deadline:"Via registration portal",website:"sidelinesoccersolutions.com/events-connecter/31st-annual-western-lehigh-fall-fest",notes:"31st annual. U13+ is 11v11. Up to 5 guest players. 100% COVID refund if canceled."},
  {id:106,name:"Dillsburg Dual Shootout",host:"Dillsburg Area Soccer Club",location:"Enola, PA",distance:87,dates:"Oct 10-11, 2026",format:"11v11 (implied)",fee:"Verify in application",deadline:"dillsburgdualshootout.com",website:"dillsburgdualshootout.com",notes:"EPYSA-approved. Level of Play choices: Premier/D1/D2/D3. 5 guest players max, roster cap 18."},
  {id:107,name:"CRUSA / FC Bucks November Classic",host:"Council Rock United SA / FC Bucks",location:"Richboro, PA",distance:18,dates:"Nov 21-22, 2026",format:"11v11 confirmed",fee:"$750",deadline:"Nov 2, 2026",website:"fcbucks.com/nov-classic/",notes:"Only 18 miles away! U13-U14 fee $750. Premier/A/B divisions. Max 22 registered / 18 dress, up to 5 guest players."},
  {id:108,name:"S3 Harvest Cup",host:"Sideline Soccer Solutions (S3)",location:"Wilmington, DE",distance:26,dates:"Nov 21-22, 2026",format:"11v11 (implied)",fee:"Verify current fees",deadline:"Via registration portal",website:"sidelinesoccersolutions.com/events-connecter/s3-harvest-cup",notes:"HQ at Chase Fieldhouse, Wilmington. Roster cap 22, max 18 dressed. Up to 5 guest players."},
  {id:109,name:"Hempfield Fall Classic (College Showcase)",host:"Penn Legacy / PA Classics AC",location:"Lancaster, PA",distance:53,dates:"Nov 21-22, 2026",format:"11v11 (verify 2026)",fee:"2026 fee not yet published",deadline:"Monitor registration",website:"pennlegacy.org/tournament",notes:"Boys weekend Nov 21-22. Fee table not yet published. Optional event cancellation insurance."},
  {id:110,name:"OBGC Capital Cup",host:"OBGC + Elite Tournaments",location:"Howard/Montgomery Co., MD",distance:114,dates:"Sep 5-7, 2026",format:"11v11 confirmed",fee:"$1,150",deadline:"Aug 7, 2026",website:"elitetournaments.com/tournaments/obgc-capital-cup/",notes:"U14 confirmed 11v11. Ranked GotSport Region I Labor Day tournament. Check-in Aug 28, schedule release Aug 25."},
  {id:111,name:"SAC Columbus Day Tournament",host:"SAC + Elite Tournaments",location:"Columbia, MD",distance:103,dates:"Oct 10-11, 2026",format:"11v11 confirmed",fee:"$1,150",deadline:"Sep 9, 2026",website:"elitetournaments.com/tournaments/sac-columbus-day-tournament/",notes:"U14 confirmed 11v11. Roster 22, check-in deadline Oct 2. Player pass required."},
  {id:113,name:"Nation's Capital Cup Boys Weekend",host:"Elite Tournaments / McLean Youth Soccer",location:"McLean / Fairfax County, VA",distance:280,dates:"Nov 21-22, 2026",format:"11v11",fee:"$1,300",deadline:"Oct 16, 2026",website:"elitetournaments.com/tournaments/nations-capital-cup-boys-weekend/",notes:"All games on synthetic turf — weather never a factor. U14 boys: $1,300, 11v11, max 22-player roster. Teams guaranteed 3 games in championship format. Fairfax County turf complex. Strong East Coast field. Non-commuting teams must book through Halpern Travel (stay-to-play). One of the top late-November fall events in the region."},
  {id:112,name:"Columbia Fall Classic Boys Weekend",host:"Elite Tournaments",location:"Columbia, MD",distance:103,dates:"Nov 14-15, 2026",format:"11v11 confirmed",fee:"$1,125",deadline:"Oct 5, 2026",website:"elitetournaments.com/tournaments/columbia-fall-classic-boys-weekend/",notes:"U14 confirmed 11v11. Max 18 dress for U13-U15. Performance bond required for U14-U19."}
];

const WINTER_TOURNAMENTS = [
  {id:201,name:"Celtic Soccer Academy Elite Cup",host:"Celtic Soccer Academy + Elite Tournaments",location:"Howard County (Columbia area), MD",distance:103,dates:"Dec 5-6, 2026",format:"11v11 confirmed",fee:"$1,350",deadline:"Nov 5, 2026",website:"elitetournaments.com/tournaments/celtic-soccer-academy-elite-cup/",notes:"U14 confirmed 11v11, max roster 22. Schedule release Nov 20. Premium turf fields in Columbia MD area. Only winter option on the list."}
];

const SPRING_TOURNAMENTS = [
  {id:301,name:"McLean Premier Cup Full Sided Weekend",host:"McLean Youth Soccer / Elite Tournaments",location:"McLean, VA",distance:127,dates:"Mar 13-14, 2027",format:"11v11 confirmed",fee:"$1,150",deadline:"Feb 12, 2027",website:"elitetournaments.com/tournaments/mclean-premier-cup-full-sided-weekend/",notes:"U14 confirmed 11v11. Teams may roster 22 but only 18 may dress per match."},
  {id:302,name:"Spring Shootout",host:"Elite Tournaments",location:"Edgewood / Howard County, MD",distance:70,dates:"Mar 27, 2027",format:"11v11 confirmed",fee:"$775",deadline:"Feb 26, 2027",website:"elitetournaments.com/tournaments/spring-shootout/",notes:"Best value at $775. U14 explicitly 11v11. Venues: Coppermine CopperPlex and Cedar Lane Regional Park."},
  {id:303,name:"Baltimore Mania Boys Weekend",host:"Elite Tournaments / Soccer Association of Columbia",location:"Columbia, MD",distance:75,dates:"~Mar 19-21, 2027",format:"11v11",fee:"~$875",deadline:"TBD (check GotSport)",website:"elitetournaments.com/tournaments/baltimore-mania-boys-weekend/",notes:"One of the premier early-spring events on the East Coast. ~500 teams across all age groups. Held at Howard County fields in Columbia, MD. Well-organized with strong competitive field from PA, MD, VA, NJ."},
  {id:304,name:"EDP Spring Kickoff PA",host:"EDP Soccer",location:"Conshohocken, PA",distance:35,dates:"~Late Mar 2027 (1-day, TBD)",format:"11v11",fee:"~$400-500",deadline:"TBD (via EDP)",website:"edpsoccer.com/spring-kickoff-pa",notes:"One-day season opener at The Proving Grounds in Conshohocken. Boys 14U-19U play Saturdays. Quick, local start to the spring season. Minimal travel and lower entry fee. Great way to shake off winter rust before bigger events."},
  {id:305,name:"Chesapeake Cup",host:"Cecil Soccer Club / Elite Tournaments",location:"Cecil County, MD",distance:55,dates:"~Apr 3-4, 2027",format:"11v11",fee:"~$750",deadline:"TBD (via GotSport)",website:"elitetournaments.com/tournaments/chesapeake-cup/",notes:"31st+ Annual. Held near the MD/PA/DE tri-state border in Cecil County -- a short drive from Chester County. Solid early April tournament with a competitive mid-Atlantic field. Good travel value."},
  {id:306,name:"APL / ICSL Spring Showdown",host:"Atlantic Premier League / Inter County Soccer League",location:"PA / NJ Region",distance:30,dates:"~Apr 4-5, 2027",format:"11v11",fee:"~$600-700",deadline:"TBD",website:"aplsoccer.com",notes:"Regional spring showdown for teams competing in the Atlantic Premier and Inter County Soccer Leagues. Local competition with minimal travel burden. Good tune-up for the late spring tournament stretch."},
  {id:307,name:"EPIC Tournament (37th Annual)",host:"Yardley Makefield Soccer Club",location:"Yardley, PA (PA/NJ border)",distance:35,dates:"~May 7-9, 2027",format:"11v11",fee:"~$750-800",deadline:"TBD (via GotSport)",website:"ymssoccer.net/epic/",notes:"Well-established 3-day tournament at the PA/NJ border near I-295 in Bucks County. Open to all skill levels U9-U19. Short prelims seed knockout rounds — all teams guaranteed play both weekend days. Family-friendly atmosphere."},
  {id:308,name:"PA Classics Challenger Invitational (Boys)",host:"PA Classics SC",location:"West Chester area, PA",distance:20,dates:"~May 8-9, 2027",format:"11v11",fee:"~$750",deadline:"TBD (via GotSport)",website:"paclassics.org",notes:"Boys-only weekend of the annual PA Classics Challenger Invitational. Held near West Chester -- virtually zero travel for our team. Strong mid-Atlantic field from B and A level clubs. One of the closest quality spring tournaments available."},
  {id:309,name:"Mother's Day Classic",host:"Local PA Host (TBD)",location:"Central PA",distance:90,dates:"~May 8-9, 2027",format:"11v11",fee:"~$600-700",deadline:"TBD",website:"epysa.org/approved-tournaments/",notes:"Annual Mother's Day weekend tournament in Central PA, EPYSA-approved. Exact host and venue vary by year. Check EPYSA approved tournament list as 2027 details become available."},
  {id:310,name:"Braves Spring Sendoff",host:"Braves SC",location:"PA",distance:80,dates:"~May 15-16, 2027",format:"11v11",fee:"~$650-750",deadline:"TBD",website:"epysa.org/approved-tournaments/",notes:"End-of-spring EPYSA-approved tournament, typically mid-May. Serves as a season sendoff before summer. Check EPYSA listings for 2027 details."},
  {id:311,name:"White Rose Classic (York Cup)",host:"FC Ballyhoo York",location:"York, PA",distance:85,dates:"~May 15-16, 2027",format:"11v11",fee:"~$650-750",deadline:"TBD (via GotSport)",website:"epysa.org/approved-tournaments/",notes:"EPYSA-approved mid-May tournament in York County. Good central PA option for the penultimate spring weekend. Competitive field from across South-Central PA."},
  {id:312,name:"Hershey Memorial Day Challenge",host:"Hershey Soccer Club",location:"Palmyra, PA",distance:80,dates:"~May 22-25, 2027",format:"11v11",fee:"~$875-950",deadline:"~Apr 2027",website:"hersheysoccer.org/memorialday",notes:"Memorial Day weekend flagship event. High-quality fields at 500 Ridge Rd, Palmyra PA near Hersheypark. Top Draw Soccer listed. Stay-to-play required for teams 90+ miles away. Tournament Director: director@hersheysoccer.org. Strong competition from across the East Coast."},
  {id:313,name:"FC Delco Players Cup",host:"FC Delco",location:"Delaware County, PA",distance:25,dates:"~May 22-25, 2027",format:"11v11",fee:"~$875-950",deadline:"~Apr 2027",website:"fcdelco.org/tournaments/",notes:"Premier-level Memorial Day tournament drawing 800+ teams nationally. One of the most competitive spring events in the region. Local venue advantage -- Delaware County is a short drive. Excellent pre-summer tune-up against top competition."},
  {id:314,name:"Gettysburg Blue Gray Cup",host:"Gettysburg Youth Soccer / Elite Tournaments",location:"Gettysburg / Emmitsburg area",distance:100,dates:"~May 22-23, 2027",format:"11v11",fee:"~$750-850",deadline:"TBD (via GotSport)",website:"elitetournaments.com/tournaments/gettysburg-blue-gray-cup/",notes:"Memorial Day weekend at historic Gettysburg. Open U8-U19 boys and girls. Unique and memorable tournament setting near the Civil War battlefield. Managed by Elite Tournaments. Approximate 1.5 hr drive from Chester County."},
  {id:315,name:"Potomac Memorial Tournament (47th Annual)",host:"Potomac Soccer Association",location:"Maryland SoccerPlex, Boyds MD",distance:120,dates:"~May 28-31, 2027",format:"11v11",fee:"~$950-1,100",deadline:"~Apr 2027",website:"potomacsoccer.org/memorial_tournament/",notes:"Elite-level Memorial Day weekend flagship. 47th annual. Played at the Maryland SoccerPlex in Boyds MD -- top-tier facility. Boys U9-U19 elite divisions. One of the most competitive and prestigious spring tournaments in the mid-Atlantic. DC United partnership."},
  {id:316,name:"Columbia Invitational (52nd Annual)",host:"Soccer Association of Columbia / Elite Tournaments",location:"Columbia, MD",distance:80,dates:"~May 23-25, 2027",format:"11v11",fee:"~$875-950",deadline:"~Apr 2027",website:"elitetournaments.com/tournaments/columbia-invitational-soccer-tournament/",notes:"52nd annual -- one of the oldest youth soccer tournaments in the country. U8-U19 boys and girls. Memorial Day weekend. Guaranteed minimum 3 games in championship format. Awards for 1st and 2nd place. Held at Howard County fields, Columbia MD."},
  {id:318,name:"Jefferson Cup Boys Weekend",host:"Richmond United",location:"Glen Allen, VA (Richmond area)",distance:310,dates:"Feb 27-28, 2027",format:"11v11",fee:"~$1,400",deadline:"Nov 1, 2026",website:"jeffersoncup.rutournaments.com",notes:"One of the most prestigious youth soccer tournaments in the US. U13-U14 play 11v11. Held at the Striker\'s Edge Soccer Center complex in Glen Allen VA. Massive field of elite teams from across the East Coast. Top Draw Soccer rated. Fills up fast — Nov 1 deadline. Contact: jeffersoncup@richmondunited.com."},
  {id:319,name:"Adidas National Cup",host:"Richmond United / Adidas",location:"Richmond, VA",distance:310,dates:"~Feb 12-14, 2027",format:"11v11",fee:"~$1,100",deadline:"~Dec 2026",website:"adidasnationalcup.com",notes:"National-level showcase hosted in Richmond VA. U9-U19 boys and girls. Elite competition from across the country. Pairs well with Jefferson Cup the following weekend if committing to a Richmond trip."},
  {id:320,name:"Virginia Legacy President's Day Cup & Showcase",host:"Virginia Legacy Soccer Club",location:"Northern Virginia",distance:290,dates:"~Feb 13-15, 2027",format:"11v11",fee:"~$875-950",deadline:"~Jan 2027",website:"virginialegacytournaments.com",notes:"Presidents Day weekend showcase in Northern Virginia. U13-U15 entry fee ~$900. 100+ high quality teams. Pre-spring season competition. Good college exposure component for older age groups."},
  {id:321,name:"EDP Spring Classic",host:"EDP Soccer",location:"Hillsborough, NJ",distance:80,dates:"~Mar 13-14, 2027",format:"11v11",fee:"~$950-1,050",deadline:"~Feb 2027",website:"edpsoccer.com/spring-classic",notes:"One of EDP\'s flagship spring events. Large competitive field at Hillsborough NJ. Boys and girls 8U-19U. Excellent early-spring tournament with strong regional draw from PA, NJ, NY, DE, MD. A natural complement to EDP Summer Classic later in the year."},
  {id:317,name:"Pittsburgh Riverhounds RDA Spring Invitational",host:"Pittsburgh Riverhounds SC / RDA",location:"Pittsburgh, PA",distance:295,dates:"~May 7-9, 2027",format:"11v11",fee:"TBD",deadline:"TBD (tournaments@riverhounds.com)",website:"riverhounds.com/riverhounds-sc-tournament-series/",notes:"Official tournament of the Pittsburgh Riverhounds SC Development Academy. U9-U19 boys and girls. Local teams may play a Friday night opener. Run by Riverhounds RDA directors and coaches, with PA Classics consulting. Quality fields and professional atmosphere. Contact: Justin Evans at tournaments@riverhounds.com."}
];


// ===================== SUMMER 2027 TOURNAMENTS =====================
const SUMMER27_TOURNAMENTS = [
  {id:401,name:"The Cup '27",host:"Philadelphia Union / S3",location:"Conshohocken, PA",distance:5,dates:"~Jun 5-6, 2027",format:"11v11",fee:"~$950-1,050",deadline:"~Apr 2027",website:"philadelphiaunion.com/youth/tournaments/the_cup",notes:"Annual flagship event at WSFS Bank Sportsplex in Conshy. Elite showcase atmosphere. Our home tournament — can't get closer. Typically sells out early. Keep an eye on registration."},
  {id:402,name:"Lehigh Valley YSL Tournament (47th Annual)",host:"Lehigh Valley YSL",location:"Allentown area, PA",distance:50,dates:"~Jun 5-6, 2027",format:"11v11",fee:"~$650-750",deadline:"~Apr 2027",website:"lehighvalleyysl.com",notes:"One of the longest-running tournaments in the region. 47th annual. Solid competition from PA and NJ. Weekend overlap with several other June openers."},
  {id:403,name:"Lancaster Summer Classic",host:"Lancaster Mennonite / Sideline Soccer",location:"Lancaster, PA",distance:60,dates:"~Jun 5-6, 2027",format:"11v11",fee:"~$650-750",deadline:"~Apr 2027",website:"sidelinesoccersolutions.com/tournaments",notes:"Annual June opener in Lancaster County. Competitive mid-Atlantic field. Good weather window early June."},
  {id:404,name:"Maryland Invitational",host:"Maryland Soccer Foundation",location:"Maryland (multiple sites)",distance:80,dates:"~Jun 4-6, 2027",format:"11v11",fee:"~$750-850",deadline:"~Apr 2027",website:"marylandinvitational.com",notes:"Multi-day June event with sites across Maryland. U14 boys compete Friday-Sunday format."},
  {id:405,name:"PA Classics Mid-Atlantic Cup (20th Annual)",host:"PA Classics SC",location:"West Chester area, PA",distance:20,dates:"~Jun 12-13, 2027",format:"11v11",fee:"~$875-950",deadline:"~Apr 2027",website:"paclassics.org/mid-atlantic-cup",notes:"20th annual. Hosted by PA Classics near West Chester — minimal travel. Strong mid-Atlantic field. One of the top early-summer events in the region."},
  {id:406,name:"Mid-Atlantic Cup at Maryland SoccerPlex",host:"Maryland SoccerPlex / MDSL",location:"Boyds, MD",distance:110,dates:"~Jun 12-13, 2027",format:"11v11",fee:"~$875-950",deadline:"~Apr 2027",website:"marylandsoccerplex.com",notes:"Premium facility at the Maryland SoccerPlex in Boyds MD. High-quality turf and grass fields. Competitive showcase atmosphere."},
  {id:407,name:"Kearny Skyline Cup",host:"Kearny Soccer Association",location:"Kearny, NJ",distance:90,dates:"~Jun 12-13, 2027",format:"11v11",fee:"~$700-800",deadline:"~Apr 2027",website:"kearnysoccer.com",notes:"Historic tournament in Kearny NJ — the cradle of American soccer. Unique cultural experience. Strong NJ/NY/PA field."},
  {id:408,name:"FSCI Summer Classic and Showcase",host:"FSCI",location:"South Jersey / NJ",distance:50,dates:"~Jun 12-13, 2027",format:"11v11",fee:"~$700-800",deadline:"~Apr 2027",website:"fscisoccer.com",notes:"South Jersey summer classic with showcase component for older age groups. Good competition from PA and NJ clubs."},
  {id:409,name:"EDP Summer Classic",host:"EDP Soccer",location:"Hammonton, NJ (Tuckahoe Turf Farms)",distance:70,dates:"~Jun 19-20, 2027",format:"11v11",fee:"~$900-1,050",deadline:"~May 2027",website:"edpsoccer.com/summer-classic",notes:"One of the East Coast's premier summer tournaments. Tuckahoe Turf Farms — top-tier facility. Massive field of teams from up and down the East Coast. One of our confirmed 2026 picks — very likely a repeat."},
  {id:410,name:"Hershey Summer Classic",host:"Hershey Soccer Club",location:"Hershey, PA",distance:80,dates:"~Jun 19-20, 2027",format:"11v11",fee:"~$800-900",deadline:"~Apr 2027",website:"hersheysoccer.org",notes:"Annual June classic near Hersheypark. Good PA-region competition. Quality fields and well-organized event."},
  {id:411,name:"Mason Dixon Cup",host:"Mason Dixon Soccer",location:"York / Frederick area",distance:90,dates:"~Jun 19-20, 2027",format:"11v11",fee:"~$700-800",deadline:"~Apr 2027",website:"masondixonsoccer.com",notes:"Annual summer classic along the PA/MD border. Good mix of PA and MD teams. Comfortable June weekend event."},
  {id:412,name:"NRSA Father's Day Cup",host:"NRSA / Local PA Club",location:"Chester County area, PA",distance:20,dates:"~Jun 19-20, 2027",format:"11v11",fee:"~$650-750",deadline:"~May 2027",website:"epysa.org/approved-tournaments/",notes:"Father's Day weekend tournament close to home. Check EPYSA listings for 2027 host confirmation. One of the lowest-travel summer options."},
  {id:413,name:"Liberty Summer Cup",host:"Liberty SC",location:"Bethlehem, PA",distance:55,dates:"~Jun 26-27, 2027",format:"11v11",fee:"~$700-800",deadline:"~May 2027",website:"libertyscpa.com",notes:"Summer classic in the Lehigh Valley. Competitive field from PA and surrounding states."},
  {id:414,name:"NSA Summer Kickoff (52nd Annual)",host:"Northern Soccer Association",location:"Central NJ",distance:75,dates:"~Jun 26-27, 2027",format:"11v11",fee:"~$800-900",deadline:"~May 2027",website:"nsasoccer.org",notes:"52nd annual — one of the oldest youth soccer tournaments in the US. NJ-based with strong PA/NY/MD participation. Excellent competitive field."},
  {id:415,name:"Pocono Mountain Cup",host:"Pocono Mountain Soccer",location:"Pocono area, PA",distance:75,dates:"~Jun 26-27, 2027",format:"11v11",fee:"~$700-800",deadline:"~May 2027",website:"poconomountaincup.com",notes:"Summer tournament in the scenic Pocono Mountains. Good for teams wanting a getaway feel with quality competition."},
  {id:416,name:"CenPenn Summer Cup",host:"Central PA Soccer",location:"Central PA",distance:90,dates:"~Jun 26-27, 2027",format:"11v11",fee:"~$650-750",deadline:"~May 2027",website:"epysa.org/approved-tournaments/",notes:"Late June Central PA tournament. Check EPYSA for 2027 host details. Regional competition, moderate travel."},
  {id:417,name:"Independence Cup Long Island",host:"Globall Competitions",location:"Uniondale, NY (Nassau County)",distance:130,dates:"~Jun 26-27, 2027",format:"11v11",fee:"TBD",deadline:"~May 2027",website:"indycupli.com",notes:"Annual summer tournament on Long Island. Strong NY/NJ/CT/PA field. Nassau County Mitchel Athletic Complex."},
  {id:418,name:"Steel United Summer Trophy (13th Annual)",host:"Steel United FC",location:"Pittsburgh area, PA",distance:290,dates:"~Jul 10-11, 2027",format:"11v11",fee:"~$750-850",deadline:"~May 2027",website:"steelunited.com",notes:"13th annual. Western PA summer tournament run by Steel United FC. Worth considering for teams open to the Pittsburgh trip."},
  {id:419,name:"Lititz Summer Showcase",host:"Lititz Soccer Club",location:"Lititz, PA",distance:60,dates:"~Jul 10-11, 2027",format:"11v11",fee:"~$800-900",deadline:"~May 2027",website:"lititzsc.com",notes:"One of our confirmed Summer '26 picks — quality showcase event in Lancaster County. Expect to return. Top mid-summer option with competitive showcase field."},
  {id:420,name:"Central Jersey Invitational",host:"EDP Soccer / Central NJ",location:"Central NJ",distance:70,dates:"~Jul 10-11, 2027",format:"11v11",fee:"~$850-950",deadline:"~May 2027",website:"edpsoccer.com/central-jersey-invitational",notes:"Mid-July EDP event in Central NJ. Strong regional draw from PA, NJ, NY, DE, MD. Good mid-summer competitive option."},
  {id:421,name:"Leon Grenko Soccer Tournament",host:"Local PA Club",location:"PA",distance:50,dates:"~Jul 10-11, 2027",format:"11v11",fee:"~$650-750",deadline:"~May 2027",website:"epysa.org/approved-tournaments/",notes:"EPYSA-approved annual summer tournament. Check listings for 2027 host confirmation."},
  {id:422,name:"EDP Summer Sizzler",host:"EDP Soccer",location:"NJ / PA region",distance:65,dates:"~Jul 24-25, 2027",format:"11v11",fee:"~$900-1,000",deadline:"~May 2027",website:"edpsoccer.com/summer-sizzler",notes:"Late July EDP event. Great follow-up to the EDP Summer Classic earlier in the summer. Completes a natural EDP double for the season."},
  {id:423,name:"Greystone Cup",host:"Greystone FC",location:"NJ",distance:80,dates:"~Jul 24-25, 2027",format:"11v11",fee:"~$750-850",deadline:"~May 2027",website:"greystonesc.com",notes:"Annual late July NJ tournament. Competitive field from the tristate area. Good late-summer tune-up before August events."},
  {id:424,name:"Philly Summer Shootout",host:"Local PA Host",location:"Philadelphia area, PA",distance:25,dates:"~Jul 24-25, 2027",format:"11v11",fee:"~$700-800",deadline:"~May 2027",website:"epysa.org/approved-tournaments/",notes:"Late July local event near Philadelphia. Minimal travel, good late-summer competition. Check EPYSA for 2027 host confirmation."},
  {id:425,name:"Liberty Cup Long Island",host:"Liberty Bucks FC",location:"Long Island, NY",distance:130,dates:"~Jul 24-25, 2027",format:"11v11",fee:"~$800-900",deadline:"~May 2027",website:"libertybucksfc.com",notes:"Late July Long Island tournament. Strong NY/NJ/CT field for teams comfortable with the drive."},
  {id:426,name:"CRUSA Invitational (18th Annual)",host:"CRUSA FC",location:"Ocean County, NJ",distance:80,dates:"~Jul 31-Aug 1, 2027",format:"11v11",fee:"~$900-1,000",deadline:"~May 2027",website:"crusasoccer.org",notes:"18th annual. Competitive elite field from NJ, PA, NY, DE, MD. Shore area venue — teams often combine with a family beach trip. One of the better late-summer events on the calendar."},
  {id:427,name:"Penn Fusion Summer Classic (39th Annual)",host:"Penn Fusion SA / S3",location:"West Chester, PA",distance:25,dates:"~Aug 7-8, 2027",format:"11v11",fee:"~$700-850",deadline:"~Jun 2027",website:"pennfusion.org/tournaments",notes:"39th annual. Our Summer '26 confirmed (Possibility) pick — good bet to repeat. Home-area tournament near West Chester. Pre-fall tune-up. Boys 1-day format."},
  {id:428,name:"Philadelphia Union Summer Cooldown",host:"Philadelphia Union / S3",location:"Conshohocken, PA",distance:5,dates:"~Aug 7-8, 2027",format:"11v11",fee:"~$800-900",deadline:"~Jun 2027",website:"philadelphiaunion.com",notes:"Late summer WSFS Bank Sportsplex event. Near-zero travel. Great pre-season tune-up before fall league play resumes. Strong local/regional field."},
  {id:429,name:"Kick-Off Classic",host:"Local PA Club",location:"PA",distance:50,dates:"~Aug 8, 2027",format:"11v11",fee:"~$600-700",deadline:"~Jun 2027",website:"epysa.org/approved-tournaments/",notes:"Annual late-summer 1-day event. Good pre-fall kickoff. Check EPYSA for 2027 confirmation."},
  {id:430,name:"Pittsburgh Riverhounds Classic",host:"Pittsburgh Riverhounds SC",location:"Pittsburgh, PA",distance:295,dates:"~Aug 28-30, 2027",format:"11v11",fee:"TBD",deadline:"TBD (tournaments@riverhounds.com)",website:"riverhounds.com/riverhounds-sc-tournament-series/",notes:"Annual Riverhounds SC flagship tournament. U9-U15 boys and girls. Professionally run by Riverhounds Development Academy staff. Great if the team is up for a Pittsburgh road trip to close out the summer."}
];

// ===================== LIVE DATA =====================
let scheduleItems = [];
let announcementItems = [];
let venueItems = [];
let allVotesFall = {}, allNotesFall = {};
let allVotesWinter = {}, allNotesWinter = {};
let allVotesSpring = {}, allNotesSpring = {};
let allVotesSummer27 = {}, allNotesSummer27 = {};

// ===================== STATE =====================
let activeSeason = 'summer';
let _summerFilter = 'all', _summerSort = 'date';
let seasonSorts = {fall:'date', winter:'date', spring:'date', summer27:'date'};
let editingEventId = null;
let editingAnnId = null;
let editingVenueId = null;
const TOTAL_CREDITS = 1000;
const MAX_PER_TOURNAMENT = 200;
let localCreditsFall = {}, localCreditsWinter = {}, localCreditsSpring = {}, localCreditsSummer27 = {};
let creditSaveTimers = {};
const pendingCreditSaves = new Set();
let showPastEvents = false;
let showPastCondSessions = false;

function getSeasonVotes(s)    { return s==='fall'?allVotesFall : s==='winter'?allVotesWinter : s==='spring'?allVotesSpring : allVotesSummer27; }
function getSeasonNotes(s)    { return s==='fall'?allNotesFall : s==='winter'?allNotesWinter : s==='spring'?allNotesSpring : allNotesSummer27; }
function getSeasonCredits(s)  { return s==='fall'?localCreditsFall : s==='winter'?localCreditsWinter : s==='spring'?localCreditsSpring : localCreditsSummer27; }
function setSeasonCredits(s,v){ if(s==='fall')localCreditsFall=v; else if(s==='winter')localCreditsWinter=v; else if(s==='spring')localCreditsSpring=v; else localCreditsSummer27=v; }
function getSeasonTournaments(s){ return s==='fall'?FALL_TOURNAMENTS : s==='winter'?WINTER_TOURNAMENTS : s==='spring'?SPRING_TOURNAMENTS : s==='summer27'?SUMMER27_TOURNAMENTS : SUMMER_TOURNAMENTS; }
function getSeasonCollection(s){ return s==='summer27'?'votes_summer27':'votes_'+s; }
function getVoterName()    { return localStorage.getItem('f6ad_voter') || ''; }
function saveVoterName(n)  { localStorage.setItem('f6ad_voter', n); }
